---
- name: Ensure .ssh directory exists for root
  file:
    path: /root/.ssh
    state: directory
    mode: '0700'

- name: Add authorized keys for root
  authorized_key:
    user: root
    key: "{{ item }}"
    state: present
  loop: "{{ ssh_public_keys }}"

- name: Ensure permissions on authorized_keys
  file:
    path: /root/.ssh/authorized_keys
    mode: '0600'

- name: Allow root login via SSH
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: 'PermitRootLogin yes'
  notify: restart sshd
