---
- name: Ensure this role runs only on RedHat family
  fail:
    msg: "This role supports only RHEL-family systems."
  when: ansible_os_family != "RedHat"

- name: Install MySQL server from local repos only on RHEL 8
  dnf:
    name: mysql-server
    state: present
    when: ansible_distribution_major_version | int == 8

- name: Install MySQL server on RHEL 10
  dnf:
    name: mysql8.4-server
    state: present
  when: ansible_distribution_major_version | int == 10

- name: Ensure mysqld service is enabled and started
  service:
    name: mysqld
    state: started
    enabled: yes

- name: Configure MySQL custom settings
  copy:
    dest: /etc/my.cnf.d/99-custom.cnf
    mode: "0644"
    content: |
      [mysqld]
      bind-address = {{ mysql_bind_address }}
      port = {{ mysql_port }}
  notify: restart mysqld
